name: Deploy to fronted Nuxt JS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install
      - name: Build the app
        run: yarn build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MAIN_SECRETS_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          source: "./"
          target: "/www/wwwroot/citydeft.com"
      - name: Restart Node.js project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart bt