name: Deploy to frontend Nuxt JS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Remove old files
        run: ssh -i ${{ secrets.MAIN_SECRETS_KEY }} ${{ secrets.SERVER_USER_NAME }}@${{ secrets.SERVER_HOST }} "rm -rf /var/www/citydeft.com/*"

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MAIN_SECRETS_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          source: "./"
          target: "/var/www/citydeft.com"

      - name: Restart app using PM2
        run: ssh -i ${{ secrets.MAIN_SECRETS_KEY }} ${{ secrets.SERVER_USER_NAME }}@${{ secrets.SERVER_HOST }} "cd /var/www/citydeft.com && yarn && pm2 restart all"
