name: Deploy to fronted Nuxt JS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... предыдущие шаги (checkout, cache, install) ...
      
      # Убираем шаг Build, если он не нужен
      # - name: Build the app
      #   run: yarn build
      
      # Шаг для деплоя на сервер
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MAIN_SECRETS_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          SOURCE: "./"
          TARGET: "/www/wwwroot/citydeft.com"

      # Шаг для запуска приложения на сервере
      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.MAIN_SECRETS_KEY }}
          script: |
            cd /www/wwwroot/citydeft.com
            pm2 restart all # или любая другая команда для запуска/перезапуска вашего приложения
